/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package baocaopizza.java;

import javax.swing.JFrame;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
/**
 *
 * @author DELL INSPIRON 5625
 */
public class frmHoaDon extends javax.swing.JFrame {

    /**
     * Creates new form fromHoaDon
     */
    KetNoi kn = new KetNoi();
    

    public frmHoaDon() {
        initComponents();
//        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        setLocationRelativeTo(null);
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmnChiTietHD = new javax.swing.JPopupMenu();
        mniXoaSP = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbLoaiSP = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_SP = new javax.swing.JTable();
        btnTimKiem = new javax.swing.JButton();
        txtTatCaSP = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        txtDiachi = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_HoaDon = new javax.swing.JTable();
        cmbTenNV = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        btnTaoHoaDon = new javax.swing.JButton();
        spnNgayLap = new javax.swing.JSpinner();
        btnTroLai = new javax.swing.JButton();

        mniXoaSP.setText("Xóa sản phẩm");
        mniXoaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniXoaSPActionPerformed(evt);
            }
        });
        pmnChiTietHD.add(mniXoaSP);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thông tin sản phẩm");
        setLocation(new java.awt.Point(100, 20));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin sản phẩm"))));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tìm kiếm sản phẩm");

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Chọn loại sản phẩm");

        cmbLoaiSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLoaiSPActionPerformed(evt);
            }
        });

        tb_SP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Giá"
            }
        ));
        tb_SP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_SPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_SP);
        if (tb_SP.getColumnModel().getColumnCount() > 0) {
            tb_SP.getColumnModel().getColumn(0).setPreferredWidth(50);
            tb_SP.getColumnModel().getColumn(1).setPreferredWidth(200);
            tb_SP.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        txtTatCaSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTatCaSP.setText("Tất cả sp");
        txtTatCaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTatCaSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTatCaSP))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtTimKiem)
                            .addGap(18, 18, 18)
                            .addComponent(btnTimKiem))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtTatCaSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin hóa đơn"));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã HD");

        txtMaHD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ngày lập");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Mã nhân viên");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Tên khách hàng");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Địa chỉ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Số điện thoại");

        txtTenKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtDiachi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tb_HoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên SP", "Số lượng", "Giá", "Thành tiền"
            }
        ));
        tb_HoaDon.setComponentPopupMenu(pmnChiTietHD);
        jScrollPane2.setViewportView(tb_HoaDon);
        if (tb_HoaDon.getColumnModel().getColumnCount() > 0) {
            tb_HoaDon.getColumnModel().getColumn(0).setPreferredWidth(15);
            tb_HoaDon.getColumnModel().getColumn(1).setPreferredWidth(300);
            tb_HoaDon.getColumnModel().getColumn(2).setPreferredWidth(25);
            tb_HoaDon.getColumnModel().getColumn(3).setPreferredWidth(80);
            tb_HoaDon.getColumnModel().getColumn(4).setPreferredWidth(80);
        }

        cmbTenNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTenNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTenNVActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Tổng tiền");

        txtTongTien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTongTien.setForeground(java.awt.Color.red);
        txtTongTien.setEnabled(false);

        btnTaoHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTaoHoaDon.setText("Tạo hóa đơn");
        btnTaoHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoHoaDonActionPerformed(evt);
            }
        });

        spnNgayLap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        spnNgayLap.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(spnNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbTenNV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(155, 155, 155)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtDiachi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(txtTenKH, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSDT)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel9)
                        .addGap(37, 37, 37)
                        .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157)
                        .addComponent(btnTaoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel7)
                        .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spnNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTaoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btnTroLai.setText("Trở Lại");
        btnTroLai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTroLaiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnTroLai)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTroLai)
                        .addGap(21, 21, 21))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    Tim kiem san pham theo ten
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String query = "select MaSP, TenSP, DonGia from SanPham where TenSP Like '%"+txtTimKiem.getText()+ "%'";
        showDataSP(query);
    }//GEN-LAST:event_btnTimKiemActionPerformed

//    Cell click vao Table San Pham
    private void tb_SPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_SPMouseClicked
        // TODO add your handling code here:
        int selectRow = tb_SP.getSelectedRow();
        try{
            DefaultTableModel model = (DefaultTableModel)tb_SP.getModel();

            String id = model.getValueAt(selectRow, 0).toString();
//            String name = model.getValueAt(selectRow, 1).toString();
            String price = model.getValueAt(selectRow, 2).toString();
            
            // Mo jFDia lay so luong
            frmDiaNhapSoLuong frm = new frmDiaNhapSoLuong(this, true);
            frm.setVisible(true);
            int sl = frm.SoLuong;
            float thanhTien = sl * Float.parseFloat(price);


            DefaultTableModel tableModel;
            tableModel = (DefaultTableModel)tb_HoaDon.getModel();

            Object obj[] = new Object[5];
            obj[0] = tableModel.getRowCount() + 1;
            obj[1] = id;
            obj[2] = sl;
            obj[3] = price;
            obj[4] = thanhTien;


            tableModel.addRow(obj);
            txtTongTien.setText(String.valueOf(tongTien()));
        }
        catch(Exception e){
            System.out.println("Loi mouseClicked");
        }
        
    }//GEN-LAST:event_tb_SPMouseClicked

    private void cmbLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLoaiSPActionPerformed
        // TODO add your handling code here:
        int ind = cmbLoaiSP.getSelectedIndex();
        String query = "select MaSP, TenSP, DonGia from SanPham where MaLoaiSP = '"+cmbLoaiSP.getItemAt(ind)+ "'";
        showDataSP(query);
        
    }//GEN-LAST:event_cmbLoaiSPActionPerformed

    private void mniXoaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniXoaSPActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbModel = (DefaultTableModel) tb_HoaDon.getModel();
        int viTri = tb_HoaDon.getSelectedRow();
        if(viTri >= 0){
            tbModel.removeRow(viTri);
            for(int i=viTri;i<tb_HoaDon.getRowCount();i++){
                tb_HoaDon.setValueAt(i+1, i, 1);
            }
        }
        txtTongTien.setText(String.valueOf(tongTien()));
    }//GEN-LAST:event_mniXoaSPActionPerformed

    private void txtTatCaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTatCaSPActionPerformed
        // TODO add your handling code here:
        showData();
    }//GEN-LAST:event_txtTatCaSPActionPerformed

    private void btnTaoHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoHoaDonActionPerformed
        // TODO add your handling code here:
        boolean chk = themHD();
        if(chk){
            themCTHD();
            lamMoi();  
        }
    }//GEN-LAST:event_btnTaoHoaDonActionPerformed

    private void cmbTenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTenNVActionPerformed
        // TODO add your handling code here:
        //        Lay du lieu trong cmb
        //        int ind = cmbTenNV.getSelectedIndex();
        //        txtMaHD.setText(getTenNV().get(ind));
    }//GEN-LAST:event_cmbTenNVActionPerformed

    private void btnTroLaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTroLaiMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_btnTroLaiMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaoHoaDon;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTroLai;
    private javax.swing.JComboBox<String> cmbLoaiSP;
    private javax.swing.JComboBox<String> cmbTenNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem mniXoaSP;
    private javax.swing.JPopupMenu pmnChiTietHD;
    private javax.swing.JSpinner spnNgayLap;
    private javax.swing.JTable tb_HoaDon;
    private javax.swing.JTable tb_SP;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JButton txtTatCaSP;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables

    private void showData() {
        String query = "select MaSP, TenSP, DonGia from SanPham";
        showDataSP(query);
        showCmbTenNV();
        showCmbMaLoaiSP();

    }
    
    
    private void showDataSP(String query){
        List<SanPhamnam> lsp = new ArrayList<>();
        ResultSet rs = kn.LayDuLieu(query);
        try{
            while(rs.next()){
                SanPhamnam sp = new SanPhamnam(rs.getString("MaSP"), rs.getString("TenSP"), rs.getFloat("DonGia"));
                lsp.add(sp);
            }
            
        DefaultTableModel tableModel;
        tableModel = (DefaultTableModel)tb_SP.getModel();
        tableModel.setRowCount(0);
        lsp.forEach((x)->{
            tableModel.addRow(new Object[] {
                x.getMaSP(), x.getTenSP(), x.getDonGia()
            });
        });
        }
        catch(SQLException e){
            
        }
    }
    
    public List<String> getTenNV(){
        List<String> lTen = new ArrayList<>();
        String query = "select * from NhanVien ";
        ResultSet rs = kn.LayDuLieu(query);
        try{
            while(rs.next()){
                lTen.add(rs.getString("MaNV"));
            }
        }
        catch(SQLException e){
            
        }
        return lTen;
    }
    public void showCmbTenNV(){
        List<String> lTen = getTenNV();
        for(String s : lTen){
            cmbTenNV.addItem(s);
        }
    }
    public List<String> getMaLoaiSP(){
        List<String> lTen = new ArrayList<>();
        String query = "select * from LoaiSanPham ";
        ResultSet rs = kn.LayDuLieu(query);
        try{
            while(rs.next()){
                lTen.add(rs.getString("MaLoaiSP"));
            }
        }
        catch(SQLException e){
            
        }
        return lTen;
    }
    public void showCmbMaLoaiSP(){
        List<String> lTen = getMaLoaiSP();
        for(String s : lTen){
            cmbLoaiSP.addItem(s);
        }
    }
    public float tongTien(){
        float Tong = 0;
        for(int i=0;i<tb_HoaDon.getRowCount(); i++){
            Tong += Float.parseFloat(tb_HoaDon.getValueAt(i, 4).toString());
        }
        return Tong;
    }
    
    
    public boolean themHD(){
        String maHD = txtMaHD.getText();
        // Lấy giá trị ngày được chọn
        Date date = (Date) spnNgayLap.getValue();

        // Chuyển đổi định dạng ngày
        SimpleDateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
        String ngayLap = dateFormat.format(date);
        
        String TenNV = cmbTenNV.getSelectedItem().toString();
        String TenKh = txtTenKH.getText();
        String DiaChi = txtDiachi.getText();
        String SDT = txtSDT.getText();
        float TongT = tongTien();
        
        boolean chk = (maHD .equals("") || TenKh.equals("") || DiaChi.equals("") || tb_HoaDon.getRowCount() == 0);
        if(chk){
            JOptionPane.showMessageDialog(null, "Vui long điền đầy đủ thông tin!");
        } 
        else{
            String query = String.format("insert into tb_HoaDon values('%s', '%s', '%s', '%s', '%s', '%s','%f')", 
                  maHD, ngayLap, TenNV, TenKh, DiaChi, SDT, TongT);
            Boolean kt = kn.ThucThi(query);
            if(kt){
                 JOptionPane.showMessageDialog(null,"Tạo thành công!");
            }
            else{
                JOptionPane.showMessageDialog(null,"Tạo thất bại!");
                return false;
            }    
        }
        return !chk;
    }
    public void themCTHD(){
        int cnt = 0;
        String MaHD = txtMaHD.getText();
        String MaSP;
        int SoLuong;
        float thanhTien;
        
        for(int i=0;i<tb_HoaDon.getRowCount();i++){
            MaSP = tb_HoaDon.getValueAt(i, 1).toString();
            SoLuong =  Integer.parseInt(tb_HoaDon.getValueAt(i, 2).toString());
            thanhTien = Float.parseFloat(tb_HoaDon.getValueAt(i, 3).toString());
            
            String query = String.format("insert into tb_ChiTietHD values('%s', '%s', %d, '%f')",MaHD, MaSP, SoLuong, thanhTien);
            Boolean kt = kn.ThucThi(query);
            if(kt)
                cnt++;
        }
        if(cnt>0)
            JOptionPane.showMessageDialog(null, "Them thành công vào chi tiết hóa đơn!");
        else{
            JOptionPane.showMessageDialog(null, "Thêm vào chi tiết hóa đơn thất bại!");
        }
    }

    public void lamMoi() {
        txtTimKiem.setText("");
        txtMaHD.setText("");
        txtDiachi.setText("");
        txtSDT.setText("");
        txtTenKH.setText("");
        
        DefaultTableModel tbModel = (DefaultTableModel) tb_HoaDon.getModel();
        tbModel.setRowCount(0);
    }
    
}

