package baocaopizza.java;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author admin
 */
import java.awt.Color;
import javax.swing.JPasswordField;
import java.sql.*;
import java.util.*;

public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        jlableAnnoucement.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlableAnnoucement = new javax.swing.JLabel();
        jTPassWord = new javax.swing.JPasswordField();
        jTUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbtnLogin = new javax.swing.JButton();
        jchkbxShowPassword = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login background.PNG"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(1460, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 60, 152, -1));

        jlableAnnoucement.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlableAnnoucement.setForeground(new java.awt.Color(255, 51, 51));
        jlableAnnoucement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        jlableAnnoucement.setText("Incorrect user name or password");
        getContentPane().add(jlableAnnoucement, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 160, 305, -1));

        jTPassWord.setText("enterpassword");
        jTPassWord.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTPassWordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTPassWordFocusLost(evt);
            }
        });
        getContentPane().add(jTPassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 270, 256, -1));

        jTUserName.setText("Enter user name");
        jTUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTUserNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTUserNameFocusLost(evt);
            }
        });
        getContentPane().add(jTUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 210, 256, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("User");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 210, 37, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 270, 90, -1));

        jbtnLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnLogin.setForeground(new java.awt.Color(51, 51, 255));
        jbtnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        jbtnLogin.setText("Login");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, -1, -1));

        jchkbxShowPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jchkbxShowPassword.setForeground(new java.awt.Color(51, 51, 255));
        jchkbxShowPassword.setText("Show password");
        jchkbxShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkbxShowPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jchkbxShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 330, 146, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anh_nen_pizza.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTUserNameFocusLost
        // TODO add your handling code here:\
        jlableAnnoucement.setVisible(false);
        if(jTUserName.getText().equals(""))
        {
            jTUserName.setText("Enter user name");
            jTUserName.setForeground(new Color(0, 118, 211));
        }
    }//GEN-LAST:event_jTUserNameFocusLost

    private void jTUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTUserNameFocusGained
        // TODO add your handling code here:
        jlableAnnoucement.setVisible(false);
        if(jTUserName.getText().equals("Enter user name"))
        {
            jTUserName.setText("");
            jTUserName.setForeground(new Color(0, 118, 211));
        }  
    }//GEN-LAST:event_jTUserNameFocusGained

    private void jTPassWordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTPassWordFocusGained
        // TODO add your handling code here:
        jlableAnnoucement.setVisible(false);
        if(jTPassWord.getText().equals("enterpassword"))
        {
            jTPassWord.setText("");
            jTPassWord.setForeground(new Color(0, 118, 211));
        }
    }//GEN-LAST:event_jTPassWordFocusGained

    private void jTPassWordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTPassWordFocusLost
        // TODO add your handling code here:
         jlableAnnoucement.setVisible(false);
        if(jTPassWord.getText().equals(""))
        {
            jTPassWord.setText("enterpassword");
            jTPassWord.setForeground(new Color(0, 118, 211));
        }
    }//GEN-LAST:event_jTPassWordFocusLost

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        // TODO add your handling code here: 
        String query = String.format("select * from DangNhap where TaiKhoan='%s' and MatKhau='%s'", jTUserName.getText(), jTPassWord.getText());
        KetNoi kn = new KetNoi();
        ResultSet rs;
        
        rs = kn.LayDuLieu(query);
        int soluong = 0;
       try {
            if(rs != null)
            {
                 while(rs.next())
                { 
                    soluong++;
                    if(soluong > 1)
                         break;
                }

                if(soluong == 1)
                {
                    this.setVisible(false);
                    home frm = new home();
                    frm.setVisible(true);

                }
                else
                {
                    jlableAnnoucement.setVisible(true);
                }
            }
            else
            {
                jlableAnnoucement.setVisible(true);
                System.out.println("khong co result tra ve");
            }
       }
       catch(SQLException sql)
       {                   
       }       
    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void jchkbxShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkbxShowPasswordActionPerformed
        // TODO add your handling code here:
        if(jchkbxShowPassword.isSelected())
        {
            jTPassWord.setEchoChar((char) 0);
        }
        else
        {
            jTPassWord.setEchoChar('*');
        }
    }//GEN-LAST:event_jchkbxShowPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jTPassWord;
    private javax.swing.JTextField jTUserName;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JCheckBox jchkbxShowPassword;
    private javax.swing.JLabel jlableAnnoucement;
    // End of variables declaration//GEN-END:variables
}
